version: '2'
services:

  proxy:
     container_name: proxy
     image: markussitzmann/appserver_proxy:1
     ports: 
       - "80:80"
     networks:
       - "net"
     volumes:
       - "/var/run/docker.sock:/tmp/docker.sock:ro"


  shell:
     container_name: shell
     image: markussitzmann/appserver_shell:1
     networks:
       - "net"
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"


  appserverdb:
     container_name: appserverdb
     image: markussitzmann/appserver_postgres:1
     networks:
       - "net"
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - PGDATA=/home/appserver/data/appserverdb/pgdata
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"
     command: postgres


  rdkitdb:
     container_name: rdkitdb
     image: markussitzmann/appserver_rdkit:1
     networks:
       - "net"
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - PGDATA=/home/appserver/data/rdkitdb/pgdata
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"
     command: postgres


  cmsdb:
     container_name: cmsdb
     image: markussitzmann/appserver_postgres:1
     networks:
       - "net"
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - PGDATA=/home/appserver/data/cmsdb/pgdata
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"
       - "${APPSERVER_HOME}/media/cmsdb:/home/appserver/media/cmsdb"
     command: postgres


  cmsindex:
     container_name: cmsindex
     image: markussitzmann/appserver_elasticsearch:1
     networks:
       - "net"
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"
     environment:
       - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
       - INDEXDIR=/home/appserver/data/cmsindex

networks:
  net:


