#!/bin/bash

source ./appserver.env

mkdir -p ${APPSERVER_HOME} && \
mkdir -p ${APPSERVER_HOME}/data && \
mkdir -p ${APPSERVER_HOME}/media && \
chown -R $USER ${APPSERVER_HOME}

docker-compose build "$@" && \
docker-compose run --rm appserver bash -ci "\
    cp -r /tmp/appserver /home/appserver && \
    mv /home/appserver/appserver/* /home/appserver && \
    rm -rf /home/appserver/appserver && \
    rm /home/appserver/appserver-build && \
    mv /home/appserver/bin/docker-compose.yml /home/appserver && \
    rm -rf /home/appserver/bin && \
	cd /home/ && \
	chown -R `stat -c %g .`.`stat -c %u .` ./appserver"
docker-compose down
echo "Done."