#!/bin/bash

source ./appserver.env

if [ -z "$1" ]; then
    echo "Please specify a database container name and a dump file name in '$APPSERVER_HOME/pg-dump' directory (only file name, no path names). Exit!"
    exit 0;
fi;

CMD="\
    echo Performing drop, create, restore db &&\
    echo DROPDB -h $1 -p 5432 -U appserver appserver   &&\
	dropdb -h $1 -p 5432 -U appserver appserver  &&\
	echo CREATEDB -h $1 -p 5432 -U appserver appserver &&\
	createdb -h $1 -p 5432 -U appserver appserver  &&\
	echo PG_RESTORE -h $1 -p 5432 -U appserver -d appserver /home/appserver/pg-dump/$2 && \
	pg_restore -h $1 -p 5432 -U appserver -d appserver /home/appserver/pg-dump/$2"


docker-compose run --rm shell bash -ci "$CMD"