#!/bin/bash

source ./appserver.env

if [ -z "$1" ]; then
    echo "Please specify a database container name. Exit!"
    exit 0;
fi;

CMD="psql -h $1 -p 5432 -U appserver appserver"

docker-compose run --rm shell bash -ci "$CMD"



