version: '3'
services:

  debian:
     build:
       context: debian/
       args:
         appserver_gid: ${APPSERVER_GID}
         appserver_uid: ${APPSERVER_UID}
     image: markussitzmann/appserver_debian:1


  proxy:
     build: nginx-proxy/
     image: markussitzmann/appserver_proxy:1
     ports: 
       - "80:80"
     volumes:
       - "/var/run/docker.sock:/tmp/docker.sock:ro"


  postgres:
     build:
       context: postgres/9.5
       args:
         appserver_gid: ${APPSERVER_GID}
         appserver_uid: ${APPSERVER_UID}
     image: markussitzmann/appserver_postgres:1
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     depends_on:
       - "debian"


  conda:
     build: conda/
     image: markussitzmann/appserver_conda:1
     depends_on:
       - "debian"


  rdkit:
     build:
       context: rdkit/install
     image: markussitzmann/appserver_rdkit:1
     environment:
       - PGDATA=/opt/bin/pgdata
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     depends_on:
       - "conda"


  django:
     build: django/
     image: markussitzmann/appserver_django:1
     depends_on:
       - "rdkit"


  shell:
     build: shell/
     container_name: shell
     image: markussitzmann/appserver_shell:1
     volumes:
        - "${APPSERVER_HOME}:/home/appserver"
     depends_on:
        - "postgres"


  elasticsearch:
      build:
         context: elasticsearch/5
         args:
           appserver_gid: ${APPSERVER_GID}
           appserver_uid: ${APPSERVER_UID}
      image: markussitzmann/appserver_elasticsearch:1
      volumes:
        - "${APPSERVER_HOME}:/home/appserver"
      ports:
       - "9200:9200"


  appserver:
     build: .
     container_name: appserver
     image: markussitzmann/appserver:1
     volumes:
        - "${APPSERVER_HOME}:/home/appserver"
     depends_on:
        - "shell"
