version: '2'
services:

  debian:
     build: debian/
     image: appserver_debian_image

  proxy:
     build: nginx-proxy/
     image: appserver_proxy_image
     ports: 
       - "80:80"
     volumes:
       - "/var/run/docker.sock:/tmp/docker.sock:ro"

  postgres:
     build: postgres/9.5
     image: appserver_postgres_image
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
     env_file: 
       - appserver.env
     depends_on:
       - "debian"

  conda:
     build: conda/
     image: appserver_conda_image
     depends_on:
       - "debian"

  rdkit:
     build: rdkit/
     image: appserver_rdkit_image
     environment:
       - USER_NAME=bin
       - PGDATA=/opt/bin/pgdata
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
     depends_on:
       - "conda"

  django:
     build: django/
     image: appserver_django_image
     depends_on:
       - "rdkit"

  shell:
     container_name: shell
     image: appserver_shell_image
     build: shell/
     volumes:
        - "${APPSERVER_HOME}:/home/appserver"
     depends_on:
        - "debian"

  appserver:
     container_name: appserver
     image: appserver_image
     build: bin/
     volumes:
        - "${APPSERVER_HOME}:/home/appserver"
     depends_on:
        - "shell"

