version: '2'
services:

  debian:
     build: debian/
     image: appserver_debian_image

  proxy:
     build: nginx-proxy/
     image: appserver_proxy_image
     ports: 
       - "80:80"
     volumes:
       - "/var/run/docker.sock:/tmp/docker.sock:ro"

  postgres:
     build: postgres/9.5
     image: appserver_postgres_image
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     depends_on:
       - "debian"

  conda:
     build: conda/
     image: appserver_conda_image
     depends_on:
       - "debian"

  rdkit:
     build: rdkit/
     image: appserver_rdkit_image
     environment:
       - PGDATA=/opt/bin/pgdata
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     depends_on:
       - "conda"

  django:
     build: django/
     image: appserver_django_image
     depends_on:
       - "rdkit"

  shell:
     build: shell/
     container_name: shell
     image: appserver_shell_image

     volumes:
        - "${APPSERVER_HOME}:/home/appserver"
     depends_on:
        - "debian"

  appserver:
     build: .
     container_name: appserver
     image: appserver_image
     volumes:
        - "${APPSERVER_HOME}:/home/appserver"
     depends_on:
        - "shell"

  elasticsearch:
      build: elasticsearch/5
      image: appserver_elasticsearch_image
      volumes:
        - "${APPSERVER_HOME}:/home/appserver"
      ports:
       - "9200:9200"

