version: '2'
services:

  appserverdb:
     container_name: appserverdb
     image: appserver_postgres_image
     networks:
       - appserver_net
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
       - PGDATA=/home/appserver/appserverdb/pgdata
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"

  rdkitdb:
     container_name: rdkitdb
     image: appserver_rdkit_image
     networks:
       - appserver_net
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
       - PGDATA=/home/appserver/rdkitdb/pgdata
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"

  cmsdb:
     container_name: cmsdb
     image: appserver_postgres_image
     networks:
       - appserver_net
     environment:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
       - PGDATA=/home/appserver/cmsdb/pgdata
     volumes:
       - "${APPSERVER_HOME}:/home/appserver"
       - "/home/cmsdb/media"

networks:
  appserver_net:
    external:
      name: bin_net

